import config from "../../config";
import { TStudent } from "../students/student.interface";
import { NewUser, TUser } from "./user.interface";
import { User } from "./user.model";

const createStudentIntoDB = async (password:string,studentData: TStudent) => {

  // create user object

  const userData:Partial<TUser>={}
  
  // if password is not given, default pasword

  userData.password = password||(config.default_password as string)

  // create student role
  userData.role = 'student'

  // set manually autogenerated Id

  userData.id="20300001"
    const result = User.create(userData);
    
// create student
  if(Object.keys(result).length){
    // set id , _id as user
    studentData.id = result.id,
    studentData.user=result._id
  };

  export const UserService={
    createStudentIntoDB
  }